name: hydrodata2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numba
  - owslib
  - scipy
  - pandas
  - matplotlib
  - descartes
  - xarray
  - cartopy
  - dask
  - netCDF4
  - bottleneck
  - pycurl
  - lxml
  - pip:
    - geopandas
    - geojson
    - rasterstats
    - tables
    - mypy==0.761
